-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg1kCUP3IDiuDnTysG
Qgc36YgcX8BejI7i0wyKcPMpJW2gCgYIKoZIzj0DAQehRANCAATjI7bk66HmAVfh
IfrTQtiAuQvqYD3mqIUikAFSEsRo5WgIATFOYjxtPVvgKmp2dVFXYkRtxClJJ3Ia
UT5bE77x
-----END PRIVATE KEY-----